version: "3"

tasks:
  install:
    desc: Install the latex package locally
    cmds:
      - l3build install

  extract-dtx-docs:
    desc: Extract and convert DTX documentation to Markdown
    cmds:
      - texlua scripts/extract-dtx-docs.lua

  docs:
    desc: Build the documentation site (Quarto)
    dir: docs
    deps:
      - extract-dtx-docs
    cmds:
      - quarto render

  docs-preview:
    desc: Preview the generated documentation in a web browser
    dir: docs
    cmds:
      - quarto preview

  build-manual:
    desc: Build the complete package manual (Quarto -> LaTeX -> PDF)
    deps:
      - extract-dtx-docs
    cmds:
      - cd docs && quarto render
      - l3build-wrapped doc

  ctan:
    desc: Prepare the package for CTAN submission
    deps:
      - build-manual
    cmds:
      - l3build-wrapped ctan
