version: "3"

tasks:
  install:
    desc: Install the latex package locally
    cmds:
      - l3build install

  docs:
    desc: Extract and convert DTX documentation to Markdown
    cmds:
      - texlua scripts/extract-dtx-docs.lua

  preview-docs:
    desc: Preview the generated documentation in a web browser
    dir: docs
    cmds:
      - quarto preview

  build-manual:
    desc: Build the complete package manual (Quarto -> LaTeX -> PDF)
    cmds:
      - cd docs && quarto render
      - l3build-wrapped doc
