version: "3"

tasks:
  install:
    desc: Install the latex package locally
    cmds:
      - l3build install

  extract-dtx-docs:
    desc: Extract and convert DTX documentation to Markdown
    cmds:
      - texlua scripts/extract-dtx-docs.lua

  test:
    desc: Run the test suite, checking package functionality
    deps:
      - generate-example-images
    cmds:
      - l3build-wrapped check

  docs:
    desc: Build the documentation site (Quarto)
    dir: docs
    deps:
      - extract-dtx-docs
      - generate-example-images
    cmds:
      - quarto render

  docs-preview:
    desc: Preview the generated documentation in a web browser
    dir: docs
    cmds:
      - quarto preview

  build-manual:
    desc: Build the PDF manual
    deps:
      - extract-dtx-docs
      - generate-example-images
    cmds:
      - cd docs && quarto render --to pdf

  ctan:
    desc: Prepare the package for CTAN submission
    deps:
      - build-manual
    cmds:
      - l3build-wrapped ctan

  generate-example-images:
    desc: Compile examples and generate grid images
    cmds:
      # Generate colortheme examples from template
      - |
        cd examples
        for theme in default tomorrow paper catppuccin highcontrast; do
          for variant in light dark; do
            pdflatex -jobname="colortheme-${theme}-${variant}" \
                     -interaction=nonstopmode \
                     colortheme-template.tex
          done
        done
      # Compile other standalone examples (skip template and generated files)
      - |
        for file in examples/*.tex; do
          basename=$(basename "$file")
          if [ "$basename" != "colortheme-template.tex" ] && [ ! -f "examples/colortheme-${basename%.tex}.pdf" ]; then
            latexmk -pdf -interaction=nonstopmode -cd "$file"
          fi
        done
      # Generate grid images
      - mkdir -p docs/images
      - |
        for pdf in examples/*.pdf; do
          basename="${pdf##*/}"
          basename="${basename%.pdf}"
          ./scripts/pdf-to-grid.sh "$pdf" "docs/images/example-${basename}.png" 2 150
        done
