version: "3"

tasks:
  install:
    desc: Install the latex package locally
    cmds:
      - l3build install

  extract-dtx-docs:
    desc: Extract and convert DTX documentation to Markdown
    cmds:
      - texlua scripts/extract-dtx-docs.lua

  test:
    desc: Run the test suite, checking package functionality
    deps:
      - generate-example-images
    cmds:
      - l3build-wrapped check

  docs:
    desc: Build the documentation site (Quarto)
    dir: docs
    deps:
      - extract-dtx-docs
      - generate-example-images
    cmds:
      - quarto render

  docs-preview:
    desc: Preview the generated documentation in a web browser
    dir: docs
    cmds:
      - quarto preview

  build-manual:
    desc: Build the PDF manual
    deps:
      - extract-dtx-docs
      - generate-example-images
    cmds:
      - cd docs && quarto render --to pdf

  ctan:
    desc: Prepare the package for CTAN submission
    deps:
      - build-manual
    cmds:
      - l3build-wrapped ctan

  save-tests:
    desc: Save test expectations (fixtures) for all test files
    cmds:
      - l3build-wrapped save backgroundcolors
      - l3build-wrapped save sectionpages
      - l3build-wrapped save separation
      - l3build-wrapped save standoutnumbering
      - l3build-wrapped save test

  generate-example-images:
    desc: Compile examples and generate grid images
    cmds:
      # Generate colortheme examples from template
      - |
        cd examples
        for theme in default tomorrow paper catppuccin highcontrast; do
          for variant in light dark; do
            pdflatex -jobname="colortheme-${theme}-${variant}" \
                     -interaction=nonstopmode \
                     colortheme-template.tex
          done
        done
      # Compile other standalone examples (skip template and generated files)
      - |
        for file in examples/*.tex; do
          basename=$(basename "$file")
          if [ "$basename" != "colortheme-template.tex" ] && [ ! -f "examples/colortheme-${basename%.tex}.pdf" ]; then
            latexmk -pdf -interaction=nonstopmode -cd "$file"
          fi
        done
      # Generate grid images
      - mkdir -p docs/images
      - |
        for pdf in examples/*.pdf; do
          basename="${pdf##*/}"
          basename="${basename%.pdf}"
          ./scripts/pdf-to-grid.sh "$pdf" "docs/images/example-${basename}.png" 2 150
        done

  tugboat-submission:
    desc: Generate TUGboat article submission package
    dir: papers
    cmds:
      # Clean any previous build artifacts first
      - |
        echo "Cleaning previous build artifacts..."
        latexmk -C tugboat.tex
        cd images && latexmk -C && cd ..
        rm -f tugboat.aux tugboat.bbl tugboat.blg
      
      # Compile image .tex files to PDFs
      - |
        echo "Compiling image files..."
        cd images
        for tex_file in *.tex; do
          if [ -f "$tex_file" ]; then
            echo "  Processing $tex_file..."
            latexmk -pdf -interaction=nonstopmode "$tex_file"
          fi
        done
        cd ..
      
      # Compile the main tugboat article (multiple passes for references)
      - |
        echo "Compiling tugboat.tex..."
        latexmk -pdf -interaction=nonstopmode tugboat.tex
      
      # Create build directory and submission tar
      - |
        echo "Creating submission package..."
        mkdir -p ../build/tugboat-submission
        
        # Copy source files
        cp tugboat.tex ../build/tugboat-submission/
        cp bibliography.bib ../build/tugboat-submission/
        cp tugboat.pdf ../build/tugboat-submission/
        
        # Copy images (PDFs only, not .tex sources)
        mkdir -p ../build/tugboat-submission/images
        cp images/*.pdf ../build/tugboat-submission/images/
        
        # Create tar archive
        cd ../build
        tar czf tugboat-submission.tar.gz tugboat-submission/
        cd ..
        
        echo "Submission package created: build/tugboat-submission.tar.gz"
      
      # Clean auxiliary files
      - |
        latexmk -c tugboat.tex
        cd images && latexmk -c && cd ..
