version: "3"

tasks:
  install:
    desc: Install the latex package locally
    cmds:
      - l3build install

  extract-dtx-docs:
    desc: Extract and convert DTX documentation to Markdown
    cmds:
      - texlua scripts/extract-dtx-docs.lua

  docs:
    desc: Build the documentation site (Quarto)
    dir: docs
    deps:
      - extract-dtx-docs
    cmds:
      - quarto render

  docs-preview:
    desc: Preview the generated documentation in a web browser
    dir: docs
    cmds:
      - quarto preview

  build-manual:
    desc: Build the complete package manual (Quarto -> LaTeX -> PDF)
    deps:
      - extract-dtx-docs
    cmds:
      - cd docs && quarto render
      - l3build-wrapped doc

  ctan:
    desc: Prepare the package for CTAN submission
    deps:
      - build-manual
    cmds:
      - l3build-wrapped ctan

  compile-examples:
    desc: Compile all example presentations
    cmds:
      - cd examples/demo && latexmk -pdf -interaction=nonstopmode demo.tex
      - cd examples/colortheme-tomorrow && latexmk -pdf -interaction=nonstopmode moloch-tomorrow.tex

  generate-example-images:
    desc: Generate grid images from all compiled examples
    deps:
      - compile-examples
    cmds:
      - mkdir -p docs/images
      - ./scripts/pdf-to-grid.sh examples/demo/demo.pdf docs/images/demo-grid.png 4 150
      - ./scripts/pdf-to-grid.sh examples/colortheme-tomorrow/moloch-tomorrow.pdf docs/images/tomorrow-grid.png 4 150
      - echo "Generated example grids in docs/images/"
